CREATE  TABLE "umessage_info" (
 "id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
 "username" VARCHAR NOT NULL ,
 "time" VARCHAR NOT NULL ,
 "custom" VARCHAR NOT NULL ,
 "title" VARCHAR NOT NULL ,
 "text" VARCHAR NOT NULL
 )


